import os

INVARIANT_STYLE = "DAIKON"

RESULT_DIR = "./example/result"
ENABLE_CACHE = True
CACHE_DIR = "./example/cache"

ALLOW_FASIFY_INV = True
DISABLE_IMPLICATION_INV = True
ENABLE_INV_REDUCTION = False
ENABLE_READ_MODEL_FLATTENVALUE = True

ETHERSCAN_API_KEY = os.environ.get("ETHERSCAN_API_KEY", "")
QUICKNODE_API_KEY = os.environ.get("QUICKNODE_API_KEY", "")
